version: "3.8"

services:
    flask-app:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - "db"
        restart: on-failure
    
    db:
        build:
            context: ./schemas
            dockerfile: dockerfile
        volumes:
            - data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    data: