version: "3.8"

services:
    flask-app:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends on:
            - db
        restart: on-failure
    
    db:
        build:
            
    